# default configuration for project
# CONFIGS ?= -DICACHE_SIZE=2048 -DDCACHE_SIZE=2048 -DLMEM_LOG_SIZE=10 
# -DNUM_CORES=1 -DNUM_WARPS=1 -DNUM_THREADS=1 -DNUM_CLUSTER=1 -DNUM_SOCKETS=1


NUM_CORES ?= 1
NUM_WARPS ?= 1
NUM_THREADS ?= 4
NUM_CLUSTER ?= 1
NUM_SOCKETS ?= 1 
XLEN ?= 64 
STACK_LOG2_SIZE ?= 13

CONFIGS += -DNUM_CORES=$(NUM_CORES) 
CONFIGS += -DNUM_WARPS=$(NUM_WARPS) 
CONFIGS += -DNUM_THREADS=$(NUM_THREADS) 
CONFIGS += -DNUM_CLUSTER=$(NUM_CLUSTER) 
CONFIGS += -DNUM_SOCKETS=$(NUM_SOCKETS) 
CONFIGS += -DSTACK_LOG2_SIZE=$(STACK_LOG2_SIZE) 

include $(SRC_DIR)/$(VORTEX_MEM).mk 

GEN_ENV = MEM_BASE=$(MEM_BASE) MEM_SIZE=$(MEM_SIZE) \
          NUM_CORES=$(NUM_CORES) NUM_WARPS=$(NUM_WARPS) \
          NUM_THREADS=$(NUM_THREADS) NUM_CLUSTER=$(NUM_CLUSTER) \
          STACK_LOG2_SIZE=$(STACK_LOG2_SIZE) STARTUP_ADDR=$(STARTUP_ADDR) \
          KERNEL_SIZE=$(KERNEL_SIZE) GUARD_SIZE=$(GUARD_SIZE) 

$(shell $(GEN_ENV) python3 $(SRC_DIR)/gen_map.py > soc_config.mk 2> gen_map.err)
include soc_config.mk

ifeq ($(STACK_BASE_ADDR),)
  $(error gen_map.py fallito: $(shell cat gen_map.err))
endif


HEX = $(patsubst 0x%,%,$(1))

ifeq ($(XLEN), 64)
  CONFIGS += -DXLEN_64
  CONFIGS += -DIO_BASE_ADDR=64\'h$(call HEX,$(IO_BASE_ADDR))
  CONFIGS += -DIO_MPM_ADDR=64\'h$(call HEX,$(IO_MPM_ADDR))
  CONFIGS += -DIO_END_ADDR=64\'h$(call HEX,$(IO_END_ADDR))
  CONFIGS += -DSTARTUP_ADDR=64\'h$(call HEX,$(STARTUP_ADDR))
  CONFIGS += -DSTACK_BASE_ADDR=64\'h$(call HEX,$(STACK_BASE_ADDR))
endif


export IO_BASE_ADDR IO_MPM_ADDR IO_END_ADDR STACK_BASE_ADDR MEM_BASE MEM_SIZE \
			 DCR_BASE DCR_SIZE GPIO_BASE GPIO_SIZE CONSOLE_BASE CONSOLE_SIZE
